### ISSUE TITLE
deploy 发送安装包到无数据节点的机器上时应允许发送

### ISSUE THREAD

**Issue by mass3** [ADBSQL/AntDB#10]
deploy 发送安装包到无数据节点的机器上时应允许发送。

**Comment by wanglinn** [comment]
在扩容或版本升级等场景中，在发送安装包文件时进行条件检查：无agent活跃节点存在，无活跃数据节点存在。之前检查的是所在集群的所有机器，能够修改为若将安装包发送到A机器，只需要检测A机器是否满足检查条件即可。
commit 8c7612fe4dccb61594a024d7ffd9a283fe528024
