### ISSUE TITLE
停止coordinator操作时需要检测自定义任务中无自动删除故障coordinator任务

### ISSUE THREAD

**Issue by mass3** [ADBSQL/AntDB#11]
启动及停止coordinator操作时需要检测自定义任务中无自动删除故障coordinator处理函数monitor_handle_coordinator

**Comment by wanglinn** [comment]
自定义定时任务monitor_handle_coordinator ，在start all, stop all, start coordinator all|nodename, stop coordinator all | nodename时需要检查job表中是否有job包含monitor_handle_coordinator且status=on， 避免启停操作对pgxc_node表的修改。
commit f70168d7f42c2b025cbf6846ad1d1bb0ea3c3441
