### ISSUE TITLE
判断主备xlog是否一致时，xlog主备位置差应为0

### ISSUE THREAD

**Issue by mass3** [ADBSQL/AntDB#12]
switchover时，判断主备xlog 一致xlog主备位置差应为0

**Comment by wanglinn** [comment]
在switchover 主备切换前，进行了一些列条件检查，其中会检查主备xlog是否一致：多次循环检查，每次先在master端做checkpoint，然后检查主备xlog是否一致，而master端做checkpoint时也会产生xlog，当时做一致检测时忽略这个checkpoint的差距大小； 为保证严格一致，先改为先在master端做checkpoint，然后再多次检查主备xlog是否一致，直至差距为0才允许进一步操作。
commit 6c149c61321e6d42af78a5baf22fbe154ba9985a
