### ISSUE TITLE
需要添加switchover gtm/datanode帮助信息

### ISSUE THREAD

**Issue by mass3** [ADBSQL/AntDB#13]
需要添加switchover gtm/datanode帮助信息

**Comment by wanglinn** [comment]
添加 gtm switchover, datanode switchover 帮助信息；
\h switchover 
SWITCHOVER DATANODE SLAVE datanode_name；
SWITCHOVER GTM SLAVE gtm_name；
commit 44702d77457ef47e96a36bcb0349ad045a04698b
