### ISSUE TITLE
flush host 及 alter coordinator端口号时均涉及coordinator节点重启，会导致coordinator被当做故障移除

### ISSUE THREAD

**Issue by mass3** [ADBSQL/AntDB#14]
flush host 及 alter coordinator端口号时均涉及coordinator节点重启，需要在自动删除故障coordinator处理函数monitor_handle_coordinator 加以限制

**Comment by wanglinn** [comment]
在FLUSH HOST, ALTER COORDINATOR (PORT=X)时对job中monitor_handle_coordinator做检测
commit 69437ce9fc9291a1e2bd3ee2c7329c36eecaa416
