### ISSUE TITLE
mgr_dump --mgr_table 存在先导出potential 节点信息, 再导出sync节点信息，这样导入时报错

### ISSUE THREAD

**Issue by mass3** [ADBSQL/AntDB#15]
mgr_dump --mgr_table 存在先导出potential 节点信息, 再导出sync节点信息，这样导入时报错。

**Comment by wanglinn** [comment]
修改LIST NODE显示排序，避免mgr_dump --mgr_table导出先是potential再是sync的问题
commit fe8fe3d66e2e0b9ee18c413a3cd20920ae66f438
