### ISSUE TITLE
ADBMgr中append coordinator节点时，内部采用pg_dump方式导出表速度较慢

### ISSUE THREAD

**Issue by mass3** [ADBSQL/AntDB#2]
当前问题：
集群运行后添加新coordinator节点，现在内部使用**pg_dump方式**导出表结构。
当大量表存在时，采用这用凡是速度较慢
建议：
采取流复制到备机，然后提升为master方式，提升添加coordiantor效率。

**Comment by wanglinn** [comment]
研发讨论新增coordinator 方式为：通过pg_basebackup 方式建立指定coordinator master的备机，建立主备流复制；通过锁集群后检查主备xlog 一致时将指定的coordinator备机提升为coordinator master。
命令格式：
APPEND COORDINATOR coordinator_souce TO coordinator_dest;  --建立coordinator备机
APPEND ACTIVATE COORDINATOR coordinator_dest;  --将备机提升为主机
commit 29b1dafce4e424ba962d6c7bf3df8f433e8a87af
