### ISSUE TITLE
打开enable_cluster_plan，报错“rescan cluster reduce no support”

### ISSUE THREAD

**Issue by mass3** [ADBSQL/AntDB#28]
**打开enable_cluster_plan，报错“rescan cluster reduce no support”**
```
postgres=# set enable_cluster_plan = on;
SET
postgres=# select * from
postgres-#   int8_tbl t1 left join
postgres-#   (select q1 as x, 42 as y from int8_tbl t2) ss
postgres-#   on t1.q2 = ss.x
postgres-# where
postgres-#   1 = (select 1 from int8_tbl t3 where ss.y is not null limit 1)
postgres-# order by 1,2;
ERROR:  rescan cluster reduce no support
```
**关闭enable_cluster_plan，查询正确**
```
postgres=# set enable_cluster_plan = off;
SET
postgres=# select * from                 
  int8_tbl t1 left join
  (select q1 as x, 42 as y from int8_tbl t2) ss
  on t1.q2 = ss.x
where
  1 = (select 1 from int8_tbl t3 where ss.y is not null limit 1)
order by 1,2;
        q1        |        q2        |        x         | y  
------------------+------------------+------------------+----
              123 | 4567890123456789 | 4567890123456789 | 42
              123 | 4567890123456789 | 4567890123456789 | 42
              123 | 4567890123456789 | 4567890123456789 | 42
 4567890123456789 |              123 |              123 | 42
 4567890123456789 |              123 |              123 | 42
 4567890123456789 | 4567890123456789 | 4567890123456789 | 42
 4567890123456789 | 4567890123456789 | 4567890123456789 | 42
 4567890123456789 | 4567890123456789 | 4567890123456789 | 42
(8 rows)
```

**测试sql：**
```
CREATE TABLE INT8_TBL(q1 int8, q2 int8);
INSERT INTO INT8_TBL VALUES('  123   ','  456');
INSERT INTO INT8_TBL VALUES('123   ','4567890123456789');
INSERT INTO INT8_TBL VALUES('4567890123456789','123');
INSERT INTO INT8_TBL VALUES(+4567890123456789,'4567890123456789');
INSERT INTO INT8_TBL VALUES('+4567890123456789','-4567890123456789');
 
select * from
  int8_tbl t1 left join
  (select q1 as x, 42 as y from int8_tbl t2) ss
  on t1.q2 = ss.x
where
  1 = (select 1 from int8_tbl t3 where ss.y is not null limit 1)
order by 1,2;
```

**Comment by hsiaoby** [comment]
之前生成的SubPlan执行计划里有多余的reduce，现已更正 e38894b27b614bca7636d0585587444131732371

**Comment by mass3** [comment]
打开开关，查询结果正确。
postgres=# set enable_cluster_plan = on;
SET
postgres=#                              
select * from
  int8_tbl t1 left join
  (select q1 as x, 42 as y from int8_tbl t2) ss
  on t1.q2 = ss.x
where
  1 = (select 1 from int8_tbl t3 where ss.y is not null limit 1)
order by 1,2;
        q1        |        q2         |        x         | y  
------------------+-------------------+------------------+----
              123 |               456 |                  |   
              123 |  4567890123456789 | 4567890123456789 | 42
              123 |  4567890123456789 | 4567890123456789 | 42
              123 |  4567890123456789 | 4567890123456789 | 42
 4567890123456789 | -4567890123456789 |                  |   
 4567890123456789 |               123 |              123 | 42
 4567890123456789 |               123 |              123 | 42
 4567890123456789 |  4567890123456789 | 4567890123456789 | 42
 4567890123456789 |  4567890123456789 | 4567890123456789 | 42
 4567890123456789 |  4567890123456789 | 4567890123456789 | 42
(10 rows)
