### ISSUE TITLE
monitor监控内容获取时间段内， tps任务若停影响qps 内容显示

### ISSUE THREAD

**Issue by mass3** [ADBSQL/AntDB#3]
monitor监控内容获取时间段内tps, qps存在问题，tps任务若停影响qps 内容显示

**Comment by wanglinn** [comment]
tps, qps 数据获取从同一个视图中读取，共用同一个时间列，在tps 或者qps 任务停止情况下影响tps 或者qps 数据获取， 改为tps, qps 数据分别对应相应的时间列，避免出现该问题。
commit  a687551c1f11c41cc7944c16c29552fea3574c4f
