### ISSUE TITLE
从父表中删除数据报错“diffent TupleDesc of number attribute”

### ISSUE THREAD

**Issue by mass3** [ADBSQL/AntDB#37]
### 从父表中删除数据报“ERROR:  diffent TupleDesc of number attribute”
```
postgres=# DELETE FROM fp where f1 < 2 returning *, f3-f1;
ERROR:  diffent TupleDesc of number attribute
DETAIL:  local is 3, remote is 4
postgres=# 
```
### 测试sql：
```
create table fp(f1 int, f2 varchar(255), f3 int);
create table fp_child (fc int) INHERITS (fp);
ALTER table fp ADD COLUMN f4 int8 DEFAULT 99;
INSERT INTO fp VALUES (1,'test',42), (2,'More', 11), (3,upper('more'), 7+9);
INSERT INTO fp_child VALUES(123,'child',999,-123);
INSERT INTO fp_child VALUES(456,'child',999,-456);
UPDATE fp SET f4 = f4 + f3 WHERE f4 = 99;
DELETE FROM fp_child where fc = -123 returning *, f4-f1;
DELETE FROM fp where f1 < 2 returning *, f3-f1;
```

**Comment by constzl** [comment]
已经修正该问题。

commit f331187ccaed52ef5756d4ee33a4157b7a05c097
Author: zhangliang10 <zhangliang10@asiainfo.com>
Date:   Mon Dec 11 18:06:45 2017 +0800

    修正 bug #37:从父表中删除数据报"ERROR: diffent TupleDesc of number attribute".
    
    原因：
        FetchRemoteQuery 函数在获取一条slot时，没有检查当前handle是否可直接使用。
    
    Notes:
        由于每个NodeHandle可能在各个RemoteQuery之间切换使用，正确的处理NodeHandle的owner变的尤为重要。
