### ISSUE TITLE
通过adbmgr端set参数时，若原参数值长度大于新设置的值长度会补充空格，这样上下格式没对齐

### ISSUE THREAD

**Issue by 33adb** [ADBSQL/AntDB#5]
通过adbmgr端set节点的postgresql.conf参数，若原参数的值长度大于将要设置的值长度会补充空格，这样上下格式没对齐

**Comment by wanglinn** [comment]
在解析节点配置文件即conf文件时，对参数值前后变化，未能覆盖到值从长变短的情况，造成等号后的参数值留有一定空格（前后值长度差）。
commit 385aa63b25a7c88114b2291958188c8d4466d37c
