### ISSUE TITLE
创建表，表中有check约束，报错invalid socket

### ISSUE THREAD

**Issue by mass3** [ADBSQL/AntDB#50]
创建表，表中有check约束，报错invalid socket
```
postgres=# CREATE TABLE CHECK_TBL (x int,
postgres(# CONSTRAINT CHECK_CON CHECK (x > 3));
ERROR:  invalid socket
```
### 测试sql：
`CREATE TABLE CHECK_TBL (x int, CONSTRAINT CHECK_CON CHECK (x > 3));`

**Comment by constzl** [comment]
commit a2a0147cd26715845343787e5b6619ded5efb3da
Author: zhangliang10 <zhangliang10@asiainfo.com>
Date:   Mon Dec 18 14:36:32 2017 +0800

    修正因 4549e8579280497ab0a57b47c2e3c1fd0947b746 代码提交造成的bug。
    
    包括：#48, #49, #50
    
    原因是，缺少下发必要的 parsetree。

**Comment by mass3** [comment]
创建表，表中有check约束，功能正常。
postgres=# CREATE TABLE CHECK_TBL (x int, CONSTRAINT CHECK_CON CHECK (x > 3));
CREATE TABLE
postgres=#
