### ISSUE TITLE
rewind时对master端pg_controldata 字段‘Minimum recovery ending location’ ‘Min recovery ending loc's timeline’ 值需要检测是否为0 

### ISSUE THREAD

**Issue by 33adb** [ADBSQL/AntDB#6]
rewind时对master端pg_controldata 字段‘Minimum recovery ending location’ ‘Min recovery ending loc's timeline’ 值需要检测是否为0

**Comment by wanglinn** [comment]
对备机执行rewind操作时，需要在master端执行checkpoint操作将数据刷盘，并且查看pg_controldata内容

commit 03f38b9585027e6c3f795aa8977186e738f052c2
