### ISSUE TITLE
集群计划下，结果输出不正确并且limit失效

### ISSUE THREAD

**Issue by constzl** [ADBSQL/AntDB#61]
执行SQL：
SELECT unique2, count(1)
, (
SELECT COUNT(1)
FROM onek
WHERE odd > 10
) AS cnt
FROM tenk1
WHERE even NOT IN (
SELECT COUNT(1)
FROM tenk2
WHERE even < 100
) group by 1 order by 1 limit 10;

执行计划：
                                                                                                                                               QUERY PLAN                                                         
                                                                                       
------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
---------------------------------------------------------------------------------------
 Finalize GroupAggregate  (cost=2165.58..2446.83 rows=9375 width=20)
   Output: tenk1.unique2, count(1), $0
   Group Key: tenk1.unique2
   ->  Cluster Merge Gather  (cost=1191.12..1278.62 rows=20000 width=0)
         Remote node: 16385,16386,16387,16388
         Sort Key: tenk1.unique2
         ->  Partial GroupAggregate  (cost=791.12..878.62 rows=5000 width=12)
               Output: tenk1.unique2, PARTIAL count(1)
               Group Key: tenk1.unique2
               InitPlan 1 (returns $0)
                 ->  Cluster Reduce  (cost=10.25..11.76 rows=1 width=8)
                       Reduce: [11990 16385 16386 16387 16388]
                       ->  Finalize Aggregate  (cost=18.51..18.52 rows=1 width=8)
                             Output: count(1)
                             ->  Cluster Reduce  (cost=17.89..18.50 rows=4 width=8)
                                   Reduce: '11990'::oid
                                   ->  Partial Aggregate  (cost=21.11..21.12 rows=1 width=8)
                                         Output: PARTIAL count(1)
                                         ->  Seq Scan on public.onek  (cost=0.00..20.88 rows=95 width=0)
                                               Output: onek.unique1, onek.unique2, onek.two, onek.four, onek.ten, onek.twenty, onek.hundred, onek.thousand, onek.twothousand, onek.fivethous, onek.tenthous, onek.
odd, onek.even, onek.stringu1, onek.stringu2, onek.string4
                                               Filter: (onek.odd > 10)
                                               Remote node: 16388,16386,16387,16385
               ->  Sort  (cost=791.12..803.62 rows=5000 width=4)
                     Output: tenk1.unique2
                     Sort Key: tenk1.unique2
                     ->  Seq Scan on public.tenk1  (cost=1.18..483.93 rows=5000 width=4)
                           Output: tenk1.unique2
                           Filter: (NOT (hashed SubPlan 2))
                           Remote node: 16388,16386,16387,16385
                           SubPlan 2
                             ->  Cluster Reduce  (cost=3.21..4.71 rows=1 width=8)
                                   Reduce: [11990 16385 16386 16387 16388]
                                   ->  Finalize Aggregate  (cost=4.42..4.43 rows=1 width=8)
                                         Output: count(1)
                                         ->  Cluster Reduce  (cost=3.80..4.41 rows=4 width=8)
                                               Reduce: '11990'::oid
                                               ->  Partial Aggregate  (cost=3.50..3.51 rows=1 width=8)
                                                     Output: PARTIAL count(1)
                                                     ->  Seq Scan on public.tenk2  (cost=0.00..3.44 rows=25 width=0)
                                                           Output: tenk2.unique1, tenk2.unique2, tenk2.two, tenk2.four, tenk2.ten, tenk2.twenty, tenk2.hundred, tenk2.thousand, tenk2.twothousand, tenk2.fivethous
, tenk2.tenthous, tenk2.odd, tenk2.even, tenk2.stringu1, tenk2.stringu2, tenk2.string4
                                                           Filter: (tenk2.even < 100)
                                                           Remote node: 16388,16386,16387,16385
(42 rows)

建表SQL：
CREATE TABLE onek (
    unique1     int4,
    unique2     int4,
    two         int4,
    four        int4,
    ten         int4,
    twenty      int4,
    hundred     int4,
    thousand    int4,
    twothousand int4,
    fivethous   int4,
    tenthous    int4,
    odd         int4,
    even        int4,
    stringu1    name,
    stringu2    name,
    string4     name
);

CREATE TABLE tenk1 (
    unique1     int4,
    unique2     int4,
    two         int4,
    four        int4,
    ten         int4,
    twenty      int4,
    hundred     int4,
    thousand    int4,
    twothousand int4,
    fivethous   int4,
    tenthous    int4,
    odd         int4,
    even        int4,
    stringu1    name,
    stringu2    name,
    string4     name
) WITH OIDS;

CREATE TABLE tenk2 (
    unique1     int4,
    unique2     int4,
    two         int4,
    four        int4,
    ten         int4,
    twenty      int4,
    hundred     int4,
    thousand    int4,
    twothousand int4,
    fivethous   int4,
    tenthous    int4,
    odd         int4,
    even        int4,
    stringu1    name,
    stringu2    name,
    string4     name                                                                                                                                                                                              
);

COPY onek FROM '/home/dev/pg9.6regress/data/onek.data';
COPY tenk1 FROM '/home/dev/pg9.6regress/data/tenk.data';
COPY tenk2 FROM '/home/dev/pg9.6regress/data/tenk.data';

**Comment by mass3** [comment]
测试通过
            QUERY PLAN                                                                                                                     
                                 
------------------------------------------------------------------------------------------------------------------------------------------
------------------------------------------------------------------------------------------------------------------------------------------
---------------------------------
 Limit  (cost=10000001292.32..10000001292.56 rows=10 width=0) (actual time=186.766..186.869 rows=10 loops=1)
   Output: tenk1.unique2, (count(1)), ($0)
   ->  Cluster Merge Gather  (cost=1011.31..1014.43 rows=129 width=0) (actual time=186.763..186.863 rows=10 loops=1)
         Remote node: 16385,16386,16387
         Sort Key: tenk1.unique2
         ->  Finalize GroupAggregate  (cost=8.73..11.85 rows=43 width=20) (actual time=45.666..45.666 rows=0 loops=1)
               Output: tenk1.unique2, count(1), $0
               Group Key: tenk1.unique2
               InitPlan 1 (returns $0)
                 ->  Cluster Reduce  (cost=3.63..5.14 rows=1 width=8) (never executed)
                       Reduce: [11990 16385 16386 16387]
                       ->  Finalize Aggregate  (cost=5.26..5.27 rows=1 width=8) (actual time=101.041..101.041 rows=1 loops=1)
                             Output: count(1)
                             ->  Cluster Reduce  (cost=4.50..5.26 rows=3 width=8) (actual time=0.044..101.020 rows=4 loops=1)
                                   Reduce: '11990'::oid
                                   ->  Partial Aggregate  (cost=4.67..4.68 rows=1 width=8) (actual time=0.042..0.042 rows=1 loops=1)
                                         Output: PARTIAL count(1)
                                         ->  Seq Scan on public.onek  (cost=0.00..4.58 rows=33 width=0) (actual time=0.031..0.031 rows=0 l
oops=1)
                                               Output: onek.unique1, onek.unique2, onek.two, onek.four, onek.ten, onek.twenty, onek.hundre
d, onek.thousand, onek.twothousand, onek.fivethous, onek.tenthous, onek.odd, onek.even, onek.stringu1, onek.stringu2, onek.string4
                                               Filter: (onek.odd > 10)
                                               Remote node: 16385,16386,16387
               ->  Cluster Merge Reduce  (cost=8.73..11.17 rows=50 width=12) (actual time=45.662..45.662 rows=0 loops=1)
                     Reduce: ('[0:2]={16385,16386,16387}'::oid[])[COALESCE(int4abs((hashint4(tenk1.unique2) % 3)), 0)]
                     Sort Key: tenk1.unique2
                     ->  Partial GroupAggregate  (cost=7.71..8.58 rows=50 width=12) (actual time=45.649..45.649 rows=0 loops=1)
                           Output: tenk1.unique2, PARTIAL count(1)
                           Group Key: tenk1.unique2
                           ->  Sort  (cost=7.71..7.83 rows=50 width=4) (actual time=45.648..45.648 rows=0 loops=1)
                                 Output: tenk1.unique2
                                 Sort Key: tenk1.unique2
                                 Sort Method: quicksort  Memory: 25kB
                                 ->  Seq Scan on public.tenk1  (cost=1.71..6.30 rows=50 width=4) (actual time=0.044..0.044 rows=0 loops=1)
                                       Output: tenk1.unique2
                                       Filter: (NOT (hashed SubPlan 2))
                                       Remote node: 16385,16386,16387
                                       SubPlan 2
                                         ->  Cluster Reduce  (cost=3.63..5.14 rows=1 width=8) (never executed)
                                               Reduce: [11990 16385 16386 16387]
                                               ->  Finalize Aggregate  (cost=5.26..5.27 rows=1 width=8) (actual time=45.517..45.517 rows=1
 loops=1)
                                                     Output: count(1)
                                                     ->  Cluster Reduce  (cost=4.50..5.26 rows=3 width=8) (actual time=0.030..45.496 rows=
4 loops=1)
                                                           Reduce: '11990'::oid
                                                           ->  Partial Aggregate  (cost=4.67..4.68 rows=1 width=8) (actual time=0.026..0.0
26 rows=1 loops=1)
                                                                 Output: PARTIAL count(1)
                                                                 ->  Seq Scan on public.tenk2  (cost=0.00..4.58 rows=33 width=0) (actual t
ime=0.015..0.015 rows=0 loops=1)
                                                                       Output: tenk2.unique1, tenk2.unique2, tenk2.two, tenk2.four, tenk2.
ten, tenk2.twenty, tenk2.hundred, tenk2.thousand, tenk2.twothousand, tenk2.fivethous, tenk2.tenthous, tenk2.odd, tenk2.even, tenk2.stringu
1, tenk2.stringu2, tenk2.string4
                                                                       Filter: (tenk2.even < 100)
                                                                       Remote node: 16385,16386,16387
 Planning time: 1.651 ms
 Execution time: 226.952 ms
(50 rows)

**Comment by mass3** [comment]
下面的语句limit仍然失效
explain verbose SELECT unique2, count(1) FROM tenk1
WHERE even NOT IN (SELECT COUNT(1) FROM tenk2 WHERE even < 100) group by 1 order by 1 limit 10;


```
postgres=# explain verbose SELECT unique2, count(1) FROM tenk1
postgres-# WHERE even NOT IN (SELECT COUNT(1) FROM tenk2 WHERE even < 100) group by 1 order by 1 limit 10;
                                                                                                                                          
     QUERY PLAN                                                                                                                           
                     
------------------------------------------------------------------------------------------------------------------------------------------
------------------------------------------------------------------------------------------------------------------------------------------
---------------------
 Finalize GroupAggregate  (cost=10.71..13.62 rows=129 width=12)
   Output: tenk1.unique2, count(1)
   Group Key: tenk1.unique2
   ->  Cluster Merge Gather  (cost=10.71..11.58 rows=150 width=0)
         Remote node: 16385,16386,16387
         Sort Key: tenk1.unique2
         ->  Partial GroupAggregate  (cost=7.71..8.58 rows=50 width=12)
               Output: tenk1.unique2, PARTIAL count(1)
               Group Key: tenk1.unique2
               ->  Sort  (cost=7.71..7.83 rows=50 width=4)
                     Output: tenk1.unique2
                     Sort Key: tenk1.unique2
                     ->  Seq Scan on public.tenk1  (cost=1.71..6.30 rows=50 width=4)
                           Output: tenk1.unique2
                           Filter: (NOT (hashed SubPlan 1))
                           Remote node: 16385,16386,16387
                           SubPlan 1
                             ->  Cluster Reduce  (cost=3.63..5.14 rows=1 width=8)
                                   Reduce: [11990 16385 16386 16387]
                                   ->  Finalize Aggregate  (cost=5.26..5.27 rows=1 width=8)
                                         Output: count(1)
                                         ->  Cluster Reduce  (cost=4.50..5.26 rows=3 width=8)
                                               Reduce: '11990'::oid
                                               ->  Partial Aggregate  (cost=4.67..4.68 rows=1 width=8)
                                                     Output: PARTIAL count(1)
                                                     ->  Seq Scan on public.tenk2  (cost=0.00..4.58 rows=33 width=0)
                                                           Output: tenk2.unique1, tenk2.unique2, tenk2.two, tenk2.four, tenk2.ten, tenk2.t
wenty, tenk2.hundred, tenk2.thousand, tenk2.twothousand, tenk2.fivethous, tenk2.tenthous, tenk2.odd, tenk2.even, tenk2.stringu1, tenk2.str
ingu2, tenk2.string4
                                                           Filter: (tenk2.even < 100)
                                                           Remote node: 16385,16386,16387
(29 rows)

postgres=# 
```

**Comment by mass3** [comment]
测试通过
postgres=# \c cidb
You are now connected to database "cidb" as user "mass2".
cidb=# explain verbose SELECT unique2, count(1) FROM tenk1
cidb-# WHERE even NOT IN (SELECT COUNT(1) FROM tenk2 WHERE even < 100) group by 1 order by 1 limit 10;
                                                                                                                                          
  QUERY PLAN                                                                                                                              
               
------------------------------------------------------------------------------------------------------------------------------------------
------------------------------------------------------------------------------------------------------------------------------------------
---------------
 Limit  (cost=112.88..113.37 rows=10 width=12)
   Output: tenk1.unique2, (count(1))
   ->  GroupAggregate  (cost=112.88..358.13 rows=5000 width=12)
         Output: tenk1.unique2, count(1)
         Group Key: tenk1.unique2
