### ISSUE TITLE
switchover datanode时应允许强制切换模式

### ISSUE THREAD

**Issue by mass3** [ADBSQL/AntDB#8]
switchover datanode时应允许强制切换模式

**Comment by wanglinn** [comment]
备机节点做switchover 前，首先检查所有coordinators 上无活跃连接（pg_stat_activity上查看无活跃连接），所有datanode masters 上无连接。现在通过命令 SWITCHOVER GTM SLAVE|EXTRA nodename [force]
即在原来命令后加“FORCE” 不再去检查coordinators上的活跃连接及datanode masters上的连接。
commit 61b7b0588735c202b2f8ae13527748bbd08a42e2
